services:
  global-db:
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: global_db
      MYSQL_ROOT_PASSWORD: Mythi@2024
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

    ports:
      - '3307:3306'
